const PROJECTS=[
{year:'2025',date:'2025',title:'戈壁十年逐梦',client:'茅台1935酒 × 中戈荟',type:'活动主视觉 / 空间美陈 / 品牌物料',tags:['event','space'],cover:'gobi-kv.jpg',featured:true,summary:'以戈壁远征的天地尺度为视觉母题，建立从主画面到现场空间、展示装置和伴手物料的一体化活动形象。',role:'主视觉设计、空间美陈、延展物料与落地支持',images:['gobi-kv.jpg','gobi-space.jpg','gobi-display.jpg']},
{year:'2025',date:'2025.05',title:'粤夜悦芳香',client:'521 国际茶日 · 广州荔湾夜茶文化嘉年华',type:'整合活动视觉 / 空间美陈',tags:['event','space'],cover:'tea-kv.jpg',featured:true,summary:'把茶文化、夜间消费场景与品牌资产组合为明快的节庆语言，并延展至花艺展台、互动装置、手持物与现场导视。',role:'主 KV、现场美陈、互动装置、物料系统',images:['tea-kv.jpg','tea-space-a.jpg','tea-space-b.jpg']},
{year:'2024',date:'2024',title:'喜在卓越中升华',client:'茅台1935品牌主题活动',type:'品牌体验 / 空间美陈',tags:['space','event'],cover:'heritage-exhibit.jpg',featured:true,summary:'围绕品牌历史、产品陈列与互动传播组织空间视觉，让签到、展示、品鉴与拍照场景保持统一识别。',role:'主题视觉、空间规划、陈列美陈与延展设计',images:['heritage-exhibit.jpg','future-exhibit.jpg','assets/cases/page-33.jpg','assets/cases/page-36.jpg','assets/cases/page-42.jpg']},
{year:'2023',date:'2022—2023',title:'“越青杯”青年双创大赛',client:'广州市越秀区青年创新创业技能大赛',type:'赛事视觉系统 / 现场设计',tags:['event','digital'],cover:'youth-kv.jpg',featured:true,summary:'连续两届赛事视觉设计，以年轻、科技和城市活力为主线，覆盖主 KV、嘉宾长图、证书、舞台和会场物料。',role:'主视觉、系列长图、舞台与全套活动物料',images:['youth-kv.jpg','assets/cases/2024-page-27.jpg','assets/cases/2024-page-29.jpg','youth-stage.jpg','assets/cases/2024-page-32.jpg']},
{year:'2022',date:'2022',title:'载誉新征程',client:'广州新兴产业发展基金五周年',type:'周年整合视觉 / 展陈',tags:['event','space'],cover:'sfund-kv.jpg',featured:true,summary:'以“五周年”为核心符号建立庆典视觉系统，贯穿邀请传播、主会场、发展历程展陈、交流区和礼赠物料。',role:'主 KV、H5、空间展陈、会场与物料系统',images:['sfund-kv.jpg','assets/cases/2024-page-37.jpg','assets/cases/2024-page-40.jpg','assets/cases/2024-page-44.jpg','sfund-exhibit.jpg','assets/cases/2024-page-47.jpg']},
{year:'2022',date:'2022—2024',title:'城市与政企活动视觉',client:'文旅、科技、产业与文化项目',type:'主视觉合集',tags:['event'],cover:'assets/cases/2024-page-56.jpg',summary:'面向不同公共活动和行业会议，在明确的信息层级下建立各自的主题气质与城市识别。',role:'主视觉设计与传播延展',images:['assets/cases/2024-page-56.jpg','assets/cases/2024-page-59.jpg','assets/cases/2024-page-63.jpg']},
{year:'2021',date:'2021',title:'国际美食 · 天河滋味',client:'广州国际美食节天河分会场',type:'活动传播 / H5长图',tags:['event','digital'],cover:'assets/cases/2024-page-50.jpg',summary:'以城市夜景和年轻化节庆色彩建立传播主画面，延展至系列海报和移动端信息长图。',role:'主视觉、系列海报、H5 长图',images:['assets/cases/2024-page-50.jpg','assets/cases/2024-page-51.jpg','assets/cases/2024-page-52.jpg']},
{year:'2021',date:'2021',title:'优鲜里 APP',client:'生鲜电商概念项目',type:'UI / VIS',tags:['digital'],cover:'uxianli-ui.jpg',summary:'围绕生鲜零售场景，梳理品牌气质、信息层级和核心购物流程，形成移动端视觉概念。',role:'品牌视觉、界面设计与展示包装',images:['uxianli-ui.jpg','assets/cases/2024-page-67.jpg']},
{year:'2021',date:'2021',title:'STUDIO 三七照相馆',client:'品牌视觉概念',type:'品牌识别 / 应用系统',tags:['digital'],cover:'assets/cases/2024-page-69.jpg',summary:'以单线人物侧影为品牌核心记忆，完成标志规范与名片、包装、户外招牌等应用场景。',role:'LOGO、视觉识别与品牌应用',images:['assets/cases/2024-page-69.jpg','assets/cases/2024-page-73.jpg']},
{year:'2021',date:'2021',title:'生鲜电商视觉',client:'零售促销与内容运营',type:'电商设计 / Banner',tags:['digital'],cover:'assets/cases/2024-page-76.jpg',summary:'针对高频零售场景建立清晰、直接的促销信息结构，覆盖首页、主题会场、商品推荐与直播边框。',role:'电商会场、Banner 与运营物料',images:['assets/cases/2024-page-76.jpg','assets/cases/2024-page-78.jpg']}
];

const PROJECT_DETAILS=[
{background:'中戈荟十周年主题活动需要同时承载纪念意义、户外精神与茅台1935的品牌表达。视觉既要有远征感，也要适应舞台、美陈和小型物料等不同尺度。',goal:'建立一套有识别度、可延展、能被顺利制作的周年活动视觉系统。',concept:'以戈壁地貌、日落天际和前行轨迹为核心意象。蓝紫色表现夜幕与征途，金色承担纪念感和品牌质感，让产品成为视觉锚点，而不是简单贴放。',process:['梳理活动主题、品牌规范和现场应用清单','完成主KV构图与标题字效，确定蓝紫与鎏金色彩体系','将核心图形拆解至门头、展台、舞台和导视结构','结合制作尺寸检查文字安全区、产品比例与落地材质'],deliverables:['活动主KV','签到与舞台背景','品牌美陈装置','手举牌与伴手物料','现场延展规范'],reflection:'这类项目的关键不只是画面冲击力，而是让同一视觉在大舞台和小物料上都成立。前期就把核心元素模块化，能显著减少后续延展的重复修改。'},
{background:'首届夜茶文化嘉年华把茶文化、城市夜生活和品牌互动放在同一个现场中，内容丰富，但也容易造成画面元素堆叠。',goal:'形成轻松、年轻、适合传播和现场打卡的节庆视觉，同时保持主办方与品牌信息清楚。',concept:'从茶叶、城市夜色和“粤夜悦芳香”的语义出发，采用高饱和撞色、手写标题和层叠山形，将传统茶意转译成更年轻的市集语言。',process:['将活动信息分为主题、品牌和体验内容三个层级','先建立主KV，再提炼可复用的标题、山形和茶叶图形','设计花艺展台、产品陈列和互动打卡区域','统一扇子、手举牌、围挡及现场小物料的图形比例'],deliverables:['活动主KV','主题花艺展台','产品展示美陈','互动打卡装置','扇子与现场物料'],reflection:'文化类活动不必依赖传统纹样堆砌。保留少量文化线索，再用当代色彩和清晰层级组织内容，更容易兼顾年轻传播与现场体验。'},
{background:'品牌主题活动包含签到、产品展示、文化介绍、品鉴和合影等多种场景，需要在同一空间中维持一致的品牌叙事。',goal:'把品牌历史、产品信息与互动体验组织成连续的参观动线，并保证每个节点都适合传播拍摄。',concept:'使用品牌红、金与青绿作为主色，结合屏风、画轴、月洞门和城市轮廓，形成现代东方的空间语言。产品始终处于视觉中心，文化元素作为结构与氛围。',process:['按照来宾动线拆分签到、展示、品鉴和合影节点','建立统一的红金材质与东方框景结构','针对不同空间尺寸调整产品、标题和信息密度','与制作环节核对结构、灯光、画面裁切和观看距离'],deliverables:['签到背景','产品展示区','品牌文化展陈','品鉴交流区','合影打卡装置'],reflection:'空间视觉不能只看单张效果图。把动线、观看距离和拍照角度放进设计判断后，各区域之间才会有连续体验，而不是彼此独立的展板。'},
{background:'“越青杯”青年创新创业技能大赛连续举办，既需要延续赛事品牌资产，也要在不同届次中保持新鲜感，并适配大量嘉宾和赛程信息。',goal:'建立年轻、可信、具城市科技感的赛事视觉系统，提高多渠道传播的一致性与制作效率。',concept:'以数字序号、城市天际线和蓝色光带构建赛事识别。不同届次调整辅助色和动态线条，但保留核心版式框架，形成连续品牌记忆。',process:['整理两届赛事的主办信息、赛程和传播节点','设计主KV并制定标题、嘉宾、赛程等信息模板','延展移动端长图、证书、导视和舞台大屏','现场核对屏幕比例、拍摄画面与物料安装效果'],deliverables:['两届赛事主KV','嘉宾与赛程长图','荣誉证书','舞台与大屏','导视及现场物料'],reflection:'连续性赛事最需要的是一套可以持续更新的系统。固定核心结构、开放辅助元素，能让后续届次既保持识别又不显得重复。'},
{background:'新兴基金成立五周年，需要回顾发展历程、展示合作成果，同时传递面向下一阶段的信心。项目包含会议、展示与交流等多类空间。',goal:'围绕“五周年”建立完整的周年形象，使线上邀请、会场和发展历程展陈形成统一表达。',concept:'将数字5与向上生长的城市线条结合，采用明亮橙金色强调成果与未来。六边形关系图、时间轴和数字化信息模块负责承载较复杂的内容。',process:['提炼五周年、发展历程与合作生态三条内容线','完成主KV及移动端邀请视觉','将信息转化为时间轴、合作矩阵和成果展板','延展主会场、交流区、讲台和礼赠物料'],deliverables:['周年主KV','H5邀请长图','发展历程展','合作机构展示','主会场与交流区','礼赠与桌面物料'],reflection:'周年项目往往信息量大。先把内容结构设计好，再处理装饰风格，能避免空间里出现大量“好看但难读”的展板。'},
{background:'这是对文旅、科技、产业和文化类活动主视觉的阶段性整理。不同客户和主题差异较大，但都需要在短时间内完成清楚的信息表达。',goal:'展示面对不同项目语境时的视觉适应能力，以及在统一制作逻辑下形成差异化风格的能力。',concept:'不预设单一风格，而是从活动对象、举办城市、传播渠道和观看距离出发，选择适合的视觉母题、信息层级与色彩策略。',process:['提炼每场活动最需要被记住的主题信息','根据受众选择城市、产业、文化或数字化视觉语汇','优先保证标题与时间地点在各尺寸中的识别','完成横版、竖版及现场屏幕的适配'],deliverables:['会议与论坛主KV','文旅活动主视觉','文化主题传播图','线上线下尺寸延展'],reflection:'合集项目体现的是方法而不是单一画风：先解决信息与场景，再决定视觉语言，设计才不会变成只换标题和背景。'},
{background:'广州国际美食节天河分会场需要面向大众进行线上传播，并在移动端承载活动介绍、商户与参与信息。',goal:'在节庆氛围之外保持信息清楚，让用户能快速理解活动主题并完成浏览。',concept:'采用紫粉夜景、城市剪影和食物插画构成主画面，借助统一卡片与色块组织后续海报和H5长图。',process:['梳理主视觉与移动端长图的信息优先级','建立标题、城市夜景和吉祥物的组合关系','为不同栏目设计统一但可区分的信息卡片','校正移动端阅读字号和长图节奏'],deliverables:['活动主KV','系列传播海报','移动端H5长图','活动栏目视觉'],reflection:'移动端长图不是把海报纵向拉长。需要按滑动节奏重新组织信息，让每一屏都有明确主题和阅读停顿。'},
{background:'生鲜电商概念项目需要同时呈现品牌气质、商品分类与高频购买流程，并在有限屏幕中处理大量价格和促销信息。',goal:'建立亲切、清楚且易扩展的移动端视觉语言，展示从品牌到界面的完整思考。',concept:'以绿色作为生鲜与可靠感的主色，搭配圆角卡片、分类图标和高对比促销标签，使商品内容成为页面中心。',process:['整理首页、分类、商品和个人中心等核心流程','建立色彩、字体、图标和卡片基础规范','设计关键界面并统一价格与促销信息层级','通过展示样机检查整体品牌一致性'],deliverables:['品牌基础视觉','核心APP界面','分类与商品页面','展示样机'],reflection:'UI视觉需要服务信息效率。减少装饰、统一卡片规则和价格层级后，品牌感反而会更稳定。'},
{background:'个人摄影品牌概念需要用简洁形象建立记忆，并能够覆盖纸品、包装、店招等不同接触点。',goal:'形成具有个人气质、容易识别且适合低成本复制的品牌识别系统。',concept:'将人物侧影简化为单线标志，搭配克制的黑、白与暖棕色。图形保留手绘温度，同时通过网格规范保证应用稳定。',process:['提炼摄影品牌的人物气质和核心记忆点','绘制并简化侧影标志，测试不同尺寸识别度','建立网格、留白和基础色彩规则','延展名片、包装、门店招牌等应用'],deliverables:['品牌标志','标志网格规范','名片与包装','户外店招应用'],reflection:'小型品牌不需要复杂的视觉资产。一个有辨识度的核心图形，加上严格的留白与应用规则，就能覆盖大多数真实场景。'},
{background:'高频生鲜零售运营需要持续产出首页、促销会场、商品推荐和直播素材，内容更新速度快、价格信息多。',goal:'在保证促销信息醒目的同时，提高模板复用效率并维持品牌一致性。',concept:'以商品图片为主角，用鲜明色块区分活动栏目；通过固定标题区、价格区和行动入口建立可重复的运营版式。',process:['按照使用频率拆分首页、会场、单品和直播模板','统一标题、价格和优惠标签的视觉层级','为不同品类配置可替换的色彩与装饰模块','在批量输出中持续检查裁切与可读性'],deliverables:['首页运营Banner','主题促销会场','单品推荐图','直播视觉边框'],reflection:'运营设计的价值也体现在效率。模块化版式让批量更新更稳定，同时减少每次活动从零开始的成本。'}
];

const PROJECT_SOURCE_CONTEXT=[
'中戈荟十年军团在沙漠征途中依靠成员协作、守护初心，并在一次次征途中超越自我。十年征途所包含的探索与拼搏精神，与茅台1935“循历史而来、取匠心而作、向美好而生”的品牌理念形成呼应。项目希望借活动彰显品牌文化与实力，与中大MBA中戈荟嘉宾共同营造一场具有纪念感的酱香盛宴。',
'项目借势广州荔湾首届夜茶文化嘉年华，以“喜文化”为核心精神内核，深度融合茅台1935品牌底蕴与茅台文化。通过沉浸式场景与互动体验，传递“茅台酱香，万家共享”的品牌主张，深化市场认知并提升系列酒的品鉴体验。',
'作品集中的茅台活动板块，集中记录本人在广州腾中广告任职期间直接参与和负责的项目。项目类型主要包括广东一区授权经销商的品牌活动、特色营销、圈层赞助与快闪活动，工作内容覆盖主KV、美陈、H5邀请函、延展物料和活动资源统筹。',
'“越青杯”以服务创业青年为宗旨，面向社会征集青年创新创业项目，通过申报筛选、初赛、复赛和决赛评选优胜项目，并提供表彰、展示与宣传。赛事同时汇聚服务机构、行业专家和青年企业家，注重粤港澳青年交流，致力于打造人才链、资金链、技术链与产业链高度集聚的创新创业平台。',
'广州城投旗下新兴基金作为政府产业基金平台，以“全球孵化、中国加速、广州实践”为发展愿景，打造“母基金+S基金+直投基金”的PSD战略模式，推动政府引导基金从1.0到4.0创新迭代。五周年产业投资交流活动于广州塔二楼展示厅举行。',
'这一组活动来自本人在广东文投任职期间直接参与和负责的项目，类型涵盖活动策划、媒体服务、品牌宣传和视频，多数服务于政府端及大型B端企业。项目既包含单场活动主视觉，也包含长期品牌宣传与产业服务项目。',
'广州国际美食节天河分会场响应广州建设国际消费中心城市核心承载区的目标，深入推进“粤菜师傅”工程并擦亮“食在天河”品牌。项目以“来天河，共享国际美食之旅”为方向，融合休闲娱乐、文化旅游和亲子潮玩内容，通过主流媒体与新媒体共同营造节庆氛围。',
'该概念项目呈现从品牌视觉到移动端界面的完整过程。设计不仅处理首页、分类和商品页面，也关注促销信息、价格层级和高频零售场景中的阅读效率。',
'以个人摄影品牌为命题，从人物侧影中提炼单线标志，并继续完成网格规范、名片、包装和户外招牌应用，展示小型品牌从核心识别到真实接触点的延展逻辑。',
'电商运营项目包含多种生鲜品类与促销节点，常见输出包括首页会场、主题Banner、商品推荐、价格信息和直播素材，重点是在高频更新中保持层级清楚与品牌统一。'
];

const ARCHIVE_IMAGES=['assets/cases/2024-page-24.jpg','assets/cases/2024-page-25.jpg','assets/cases/2024-page-26.jpg','assets/cases/2024-page-27.jpg','assets/cases/2024-page-28.jpg','assets/cases/2024-page-29.jpg','assets/cases/2024-page-30.jpg','assets/cases/2024-page-31.jpg','assets/cases/2024-page-32.jpg','assets/cases/2024-page-33.jpg','assets/cases/2024-page-34.jpg','assets/cases/2024-page-36.jpg','assets/cases/2024-page-37.jpg','assets/cases/2024-page-38.jpg','assets/cases/2024-page-39.jpg','assets/cases/2024-page-40.jpg','assets/cases/2024-page-41.jpg','assets/cases/2024-page-42.jpg','assets/cases/2024-page-43.jpg','assets/cases/2024-page-44.jpg','assets/cases/2024-page-45.jpg','assets/cases/2024-page-46.jpg','assets/cases/2024-page-47.jpg','assets/cases/2024-page-48.jpg','assets/cases/2024-page-50.jpg','assets/cases/2024-page-51.jpg','assets/cases/2024-page-52.jpg','assets/cases/2024-page-53.jpg','assets/cases/2024-page-55.jpg','assets/cases/2024-page-56.jpg','assets/cases/2024-page-57.jpg','assets/cases/2024-page-58.jpg','assets/cases/2024-page-59.jpg','assets/cases/2024-page-60.jpg','assets/cases/2024-page-61.jpg','assets/cases/2024-page-62.jpg','assets/cases/2024-page-63.jpg','assets/cases/2024-page-65.jpg','assets/cases/2024-page-66.jpg','assets/cases/2024-page-67.jpg','assets/cases/2024-page-68.jpg','assets/cases/2024-page-69.jpg','assets/cases/2024-page-70.jpg','assets/cases/2024-page-71.jpg','assets/cases/2024-page-72.jpg','assets/cases/2024-page-73.jpg','assets/cases/2024-page-74.jpg','assets/cases/2024-page-76.jpg','assets/cases/2024-page-77.jpg','assets/cases/2024-page-78.jpg','assets/cases/2024-page-79.jpg','assets/cases/page-04.jpg','assets/cases/page-05.jpg','assets/cases/page-06.jpg','assets/cases/page-07.jpg','assets/cases/page-09.jpg','assets/cases/page-10.jpg','assets/cases/page-11.jpg','assets/cases/page-12.jpg','assets/cases/page-13.jpg','assets/cases/page-14.jpg','assets/cases/page-15.jpg','assets/cases/page-23.jpg','assets/cases/page-24.jpg','assets/cases/page-25.jpg','assets/cases/page-26.jpg','assets/cases/page-27.jpg','assets/cases/page-28.jpg','assets/cases/page-29.jpg','assets/cases/page-30.jpg','assets/cases/page-31.jpg','assets/cases/page-32.jpg','assets/cases/page-33.jpg','assets/cases/page-34.jpg','assets/cases/page-35.jpg','assets/cases/page-36.jpg','assets/cases/page-37.jpg','assets/cases/page-38.jpg','assets/cases/page-42.jpg','assets/cases/page-43.jpg','assets/cases/page-44.jpg','assets/cases/page-45.jpg','assets/cases/page-47.jpg','assets/cases/page-48.jpg','assets/cases/page-49.jpg','assets/cases/page-50.jpg','assets/cases/page-55.jpg','assets/cases/page-56.jpg','assets/cases/page-57.jpg','assets/cases/page-58.jpg'];
