const PROJECTS=[
{year:'2025',date:'2025',title:'戈壁十年逐梦',client:'茅台1935酒 × 中戈荟',type:'活动主视觉 / 空间美陈 / 品牌物料',tags:['event','space'],cover:'gobi-kv.jpg',featured:true,summary:'以戈壁远征的天地尺度为视觉母题，建立从主画面到现场空间、展示装置和伴手物料的一体化活动形象。',role:'主视觉设计、空间美陈、延展物料与落地支持',images:['gobi-kv.jpg','gobi-space.jpg','gobi-display.jpg']},
{year:'2025',date:'2025.05',title:'粤夜悦芳香',client:'521 国际茶日 · 广州荔湾夜茶文化嘉年华',type:'整合活动视觉 / 空间美陈',tags:['event','space'],cover:'tea-kv.jpg',featured:true,summary:'把茶文化、夜间消费场景与品牌资产组合为明快的节庆语言，并延展至花艺展台、互动装置、手持物与现场导视。',role:'主 KV、现场美陈、互动装置、物料系统',images:['tea-kv.jpg','tea-space-a.jpg','tea-space-b.jpg']},
{year:'2024',date:'2024',title:'喜在卓越中升华',client:'茅台1935品牌主题活动',type:'品牌体验 / 空间美陈',tags:['space','event'],cover:'heritage-exhibit.jpg',featured:true,summary:'围绕品牌历史、产品陈列与互动传播组织空间视觉，让签到、展示、品鉴与拍照场景保持统一识别。',role:'主题视觉、空间规划、陈列美陈与延展设计',images:['heritage-exhibit.jpg','future-exhibit.jpg','assets/cases/page-33.jpg','assets/cases/page-36.jpg','assets/cases/page-42.jpg']},
{year:'2023',date:'2022—2023',title:'“越青杯”青年双创大赛',client:'广州市越秀区青年创新创业技能大赛',type:'赛事视觉系统 / 现场设计',tags:['event','digital'],cover:'youth-kv.jpg',featured:true,summary:'连续两届赛事视觉设计，以年轻、科技和城市活力为主线，覆盖主 KV、嘉宾长图、证书、舞台和会场物料。',role:'主视觉、系列长图、舞台与全套活动物料',images:['youth-kv.jpg','assets/cases/2024-page-27.jpg','assets/cases/2024-page-29.jpg','youth-stage.jpg','assets/cases/2024-page-32.jpg']},
{year:'2022',date:'2022',title:'载誉新征程',client:'广州新兴产业发展基金五周年',type:'周年整合视觉 / 展陈',tags:['event','space'],cover:'sfund-kv.jpg',featured:true,summary:'以“五周年”为核心符号建立庆典视觉系统，贯穿邀请传播、主会场、发展历程展陈、交流区和礼赠物料。',role:'主 KV、H5、空间展陈、会场与物料系统',images:['sfund-kv.jpg','assets/cases/2024-page-37.jpg','assets/cases/2024-page-40.jpg','assets/cases/2024-page-44.jpg','sfund-exhibit.jpg','assets/cases/2024-page-47.jpg']},
{year:'2022',date:'2022—2024',title:'城市与政企活动视觉',client:'文旅、科技、产业与文化项目',type:'主视觉合集',tags:['event'],cover:'assets/cases/2024-page-56.jpg',summary:'面向不同公共活动和行业会议，在明确的信息层级下建立各自的主题气质与城市识别。',role:'主视觉设计与传播延展',images:['assets/cases/2024-page-56.jpg','assets/cases/2024-page-59.jpg','assets/cases/2024-page-63.jpg']},
{year:'2021',date:'2021',title:'国际美食 · 天河滋味',client:'广州国际美食节天河分会场',type:'活动传播 / H5长图',tags:['event','digital'],cover:'assets/cases/2024-page-50.jpg',summary:'以城市夜景和年轻化节庆色彩建立传播主画面，延展至系列海报和移动端信息长图。',role:'主视觉、系列海报、H5 长图',images:['assets/cases/2024-page-50.jpg','assets/cases/2024-page-51.jpg','assets/cases/2024-page-52.jpg']},
{year:'2021',date:'2021',title:'优鲜里 APP',client:'生鲜电商概念项目',type:'UI / VIS',tags:['digital'],cover:'uxianli-ui.jpg',summary:'围绕生鲜零售场景，梳理品牌气质、信息层级和核心购物流程，形成移动端视觉概念。',role:'品牌视觉、界面设计与展示包装',images:['uxianli-ui.jpg','assets/cases/2024-page-67.jpg']},
{year:'2021',date:'2021',title:'STUDIO 三七照相馆',client:'品牌视觉概念',type:'品牌识别 / 应用系统',tags:['digital'],cover:'assets/cases/2024-page-69.jpg',summary:'以单线人物侧影为品牌核心记忆，完成标志规范与名片、包装、户外招牌等应用场景。',role:'LOGO、视觉识别与品牌应用',images:['assets/cases/2024-page-69.jpg','assets/cases/2024-page-73.jpg']},
{year:'2021',date:'2021',title:'生鲜电商视觉',client:'零售促销与内容运营',type:'电商设计 / Banner',tags:['digital'],cover:'assets/cases/2024-page-76.jpg',summary:'针对高频零售场景建立清晰、直接的促销信息结构，覆盖首页、主题会场、商品推荐与直播边框。',role:'电商会场、Banner 与运营物料',images:['assets/cases/2024-page-76.jpg','assets/cases/2024-page-78.jpg']}
];
